apiVersion: v1
name: kube-keepalived-vip
version: 0.11
description: Highly available IP addresses and services via kube-keepalived-vip
home: https://github.com/kubernetes-retired/contrib/tree/master/keepalived-vip
engine: gotpl
