---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "kube-keepalived-vip.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.keepalived.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "kube-keepalived-vip.fullname" . }}
data:
{{- if .Values.keepalived.config }}
{{ toYaml .Values.keepalived.config | indent 2 }}
{{- end }}
{{- if .Values.keepalived.vips }}
  {{- range .Values.keepalived.vips }}
  {{ . }}: ""
  {{- end }}
{{- end }}