keepalived:
  name: keepalived
  image:
    repository: ghcr.io/ctlaltlaltc/keepalived-vip/kube-keepalived-vip
    tag: "latest"
    pullPolicy: IfNotPresent

  # Content of the configuration ConfigMap supplied to kube-keepalive-vip
  config: {}

  # Unicast uses the IP of the nodes instead of multicast. This is useful if running in cloud providers (like AWS).
  useUnicast: false

  # VRRP virtual router ID, must be unique on a particular network segment (0-255)
  vrid: 179

  # Resource allocations for the keepalived container
  resources: {}

fullnameOverride: ""
nameOverride: ""

revisionHistoryLimit: 10

# Update strategy (requires at least Kubernetes 1.6)
# A sensible policy would be:
# updateStrategy:
#   rollingUpdate:
#     maxUnavailable: 1
#   type: RollingUpdate
updateStrategy: {}

# Pod labels
podLabels: {}

# Tolerations
tolerations: []

# Node selector
nodeSelector: {}

# Pod annotations
podAnnotations: {}

rbac:
  create: true
  # serviceAccountName is only required when rbac.create is false
  serviceAccountName: default
